---
- name: Install dependencies
  package:
    name: python-docker

- name: Start watchtower
  docker_container:
    name: watchtower
    image: 'docker.io/containrrr/watchtower:armhf-0.3.2'
    env:
      WATCHTOWER_POLL_INTERVAL: '3600'
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_TIMEOUT: '30s'
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: rpi
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: '{{ watchtower_slack_url }}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart_policy: unless-stopped
