---
# Ensure ansible_default_ipv4 is set
- setup: {}

- name: Install dependencies
  package:
    name: python-docker

- name: Set up minio tenants
  loop: '{{ minio_tenants }}'
  loop_control:
    index_var: i
  include_tasks: setup-tenant.yml
