---
- setup: {}

- lineinfile:
    path: /etc/openvpn/server.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  vars:
    network: '{{ ansible_default_ipv4.network }}'
    netmask: '{{ ansible_default_ipv4.netmask }}'
    address: '{{ ansible_default_ipv4.address }}'
  loop:
    - regexp: '^push "redirect-gateway '
      state: absent
    - regexp: '^push "route '
      line: 'push "route {{ network }} {{ netmask }}"'
    - regexp: '^push "dhcp-option DNS '
      line: 'push "dhcp-option DNS {{ address }}"'
  notify:
    - Restart OpenVPN
