---
# Ensure ansible_default_ipv4 is set
- setup: {}

- name: Install dependencies
  package:
    name: python-docker

- name: Create config/data dirs
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    mode: 0755
  loop:
    - path: '{{ pihole_config_dir }}'
    - path: '{{ pihole_config_dir }}/etc-pihole'
      owner: '999'
      group: '999'
    - path: '{{ pihole_config_dir }}/etc-dnsmasq.d'

- name: Start pihole
  docker_container:
    name: pihole
    image: docker.io/pihole/pihole:latest
    dns_servers:
      - '127.0.0.1'
      - '{{ traefik_dns1 }}'
    env:
      TZ: Europe/Zurich
      WEBPASSWORD: '{{ traefik_webpassword }}'
      DNS1: '{{ traefik_dns1 }}'
      DNS2: '{{ traefik_dns2 }}'
      ServerIP: '{{ ansible_default_ipv4.address }}'
      VIRTUAL_HOST: '{{ traefik_virtual_host }}'
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:pihole.mhnet.me'
      traefik.port: '80'
      traefik.protocol: 'http'
      traefik.backend: 'pihole'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
      - '{{ pihole_config_dir }}/etc-pihole/:/etc/pihole/'
      - '{{ pihole_config_dir }}/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart_policy: unless-stopped
